train_transform:
  augments:
    - __target__: normalize_pc
    - __target__: surface_branch_cache
      cache_root: cache_surface_branches
      cache_name: surface_branches.npz
      required: false
    - __target__: add_noise
      noise_std_min: 0.005
      noise_std_max: 0.020
      noise_type: laplace
    - __target__: patch
      patch_size: 1000
      num_patches: 1
      refine_surface_branches: false

validate_transform:
  augments:
    - __target__: normalize_pc
    - __target__: surface_branch_cache
      cache_root: cache_surface_branches
      cache_name: surface_branches.npz
      required: false
    - __target__: add_noise
      noise_std_min: 0.005
      noise_std_max: 0.020
      noise_type: laplace
    - __target__: patch
      patch_size: 1000
      num_patches: 1
      refine_surface_branches: false

predict_transform: {}
