train_transform:
  augments:
    - __target__: normalize_pc
    
    - __target__: add_noise
      noise_std_min: 0.005
      noise_std_max: 0.020
    
    - __target__: patch
      patch_size: 1000
      num_patches: 1
      bridge_sample_t: true
      bridge_t_min: 0.001
      bridge_t_max: 1.0
      bridge_noise_std: 0.0

validate_transform: &validate_transform
  augments:
    - __target__: normalize_pc
    
    - __target__: add_noise
      noise_std_min: 0.005
      noise_std_max: 0.020
    
    - __target__: patch
      patch_size: 1000
      num_patches: 1
      bridge_sample_t: true
      bridge_t_min: 0.001
      bridge_t_max: 1.0
      bridge_noise_std: 0.0

predict_transform: {}
