train_transform:
  augments:
    - __target__: normalize_pc
    
    - __target__: add_noise
      noise_std_min: 0.005
      noise_std_max: 0.020
    
    - __target__: patch
      patch_size: 1000
      num_patches: 1
      mix_with_clean: true

validate_transform: &validate_transform
  augments:
    - __target__: normalize_pc
    
    - __target__: add_noise
      noise_std_min: 0.005
      noise_std_max: 0.020
    
    - __target__: patch
      patch_size: 1000
      num_patches: 1
      mix_with_clean: true

predict_transform: {}
