train_transform:
  augments:
    - __target__: normalize_pc
    
    - __target__: add_noise
      noise_std_min: 0.0
      noise_std_max: 0.025
      noise_std_distribution: log_normal
      noise_log_std: 0.35
      noise_std_floor: 0.0001
      noise_type: gaussian
    
    - __target__: patch
      patch_size: 1000
      num_patches: 1

validate_transform: &validate_transform
  augments:
    - __target__: normalize_pc
    
    - __target__: add_noise
      noise_std_min: 0.0
      noise_std_max: 0.025
      noise_type: gaussian
    
    - __target__: patch
      patch_size: 1000
      num_patches: 1

predict_transform: {}
