mode: predict
debug: False
load_ckpt: outputs/vm/checkpoints/checkpoint_best.pkl

components:
  data: predict
  transform: vm
  system: vm
  model: vm

writer:
  __target__: vm
  save_dir: outputs/vm/result/test_noisy
  save_name: denoised
  result_zip: outputs/vm/result/result.zip
