mode: predict
debug: False
load_ckpt: outputs/checkpoints/vm/checkpoint_99.pkl

components:
  data: predict
  transform: vm
  system: vm
  model: vm

writer:
  __target__: vm
  save_dir: outputs/results/test_noisy
  save_name: denoised
