mode: predict
debug: False
load_ckpt: outputs/point_net2/checkpoints/checkpoint_best.pkl

components:
  data: predict
  transform: pointnet2
  system: pointnet2
  model: pointnet2

writer:
  __target__: vm
  save_dir: outputs/point_net2/result/test_noisy
  save_name: denoised
  result_zip: outputs/point_net2/result/result.zip
