mode: predict
debug: False
load_ckpt: outputs/EdgeConv_EDM/checkpoints/checkpoint_best.pkl

components:
  data: edgeconv_baseline
  transform: edgeconv_baseline
  system: edgeconv_baseline
  model: edgeconv_baseline

writer:
  __target__: vm
  save_dir: outputs/EdgeConv_EDM/result/test_noisy
  save_name: denoised
  result_zip: outputs/EdgeConv_EDM/result/result.zip
