mode: predict
debug: False
load_ckpt: outputs_result/outputs_pointnet2_baseline/checkpoints/vm/checkpoint_best.pkl

components:
  data: predict
  transform: pointnet2
  system: pointnet2
  model: pointnet2

writer:
  __target__: vm
  save_dir: outputs_result/outputs_pointnet2_baseline/result/test_noisy
  save_name: denoised
  result_zip: outputs_result/outputs_pointnet2_baseline/result.zip
