mode: train
debug: False
load_ckpt: null

components:
  data: train
  transform: vm
  system: vm
  model: vm_dino_pretrained
  train: vm_dino_pretrained

writer:
  __target__: vm
  save_dir: outputs/result/test_noisy
  save_name: denoised
  result_zip: result.zip
