mode: train
debug: False
load_ckpt: outputs1/checkpoints/vm/checkpoint_best.pkl

components:
  data: train
  transform: vm
  system: vm
  model: vm
  train: vm

writer:
  __target__: vm
  save_dir: outputs/result/test_noisy
  save_name: denoised
  result_zip: result.zip
