loss:
  displacement_loss: 0.9
  normalized_surface_loss: 0.1

optimizer:
  __target__: adam
  lr: 0.000003

scheduler:
  __target__: reduce_on_plateau
  monitor: final_score
  mode: max
  factor: 0.8
  patience: 10
  min_lr: 0.0000003

trainer:
  epochs: 100
