loss:
  displacement_loss: 0.8
  normalized_surface_loss: 0.2

optimizer:
  __target__: adam
  lr: 0.000003
  global_encoder_lr_scale: 1.0

scheduler:
  __target__: reduce_on_plateau
  monitor: final_score
  mode: max
  factor: 0.8
  patience: 10
  min_lr: 0.0000003

trainer:
  epochs: 100
  global_encoder_freeze_epochs: 10
